# Generated by Django 5.2.10 on 2026-01-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunterprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='skills.skill'),
        ),
    ]
